### PR TITLE
File structure defined and About section created

### LINKED ISSUE #3: Create the About Section
### **User Stories**
---
As a user I want to be able to see a section with a title of about 

### **Description**
---
As a user I will see a header with the name "About", inside this section it will contain three rows that will have a paragraph of text and an image with the position of the paragraphs and images appearing in either position right or left.
image

**Acceptance Criteria**

- Should be pixel perfect  like the design above
- Lines of code should not be more than 100 lines of code
- Should be below the hero section, Should display three paragraphs of text and three images.

### PR DESCRIPTION
**Pull request by yr1404**
### Description
---
Add a bit of a description of the issue your solving

### Fixes
---
Fixes #3

## Screenshots
You can add screenshots of the end product or video

### Type of change
---
Add the type of change your pr is making
You can delete the other types of change

- [x] New Feature(non-breaking change that adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New Feature(breaking change that adds functionality)
- [x] Bug fix (breaking change which fixes an issue)

### How has this been tested?
- [x] Test A
- [x] Test B

### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by kahoragachau — CHANGES_REQUESTED** [review]
@yr1404 Great Job! 👏, One minor change, Make the background White and text black

**Comment by kahoragachau** [comment]
@yr1404 also link the issue number on the pr template
image

**Comment by yr1404** [comment]
Sure! I'll make the changes.

**Comment by yr1404** [comment]
Done. #7

**Review by kahoragachau — APPROVED** [review]

**Pull request merged**
